const pages=document.querySelectorAll('.page');
function showTab(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));window.scrollTo({top:0,behavior:'smooth'});localStorage.setItem('nexaTab',id)}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));showTab(localStorage.getItem('nexaTab')||'home');
const query=document.getElementById('query'), answerQuery=document.getElementById('answerQuery'), title=document.getElementById('answerTitle');
function runSearch(){let q=query.value.trim()||'What is an AI agent?';answerQuery.value=q;title.textContent=q;showTab('answer')}
document.getElementById('searchBtn').onclick=runSearch;query.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();runSearch()}});document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{query.value=b.dataset.q;runSearch()});document.getElementById('answerSearch').onclick=()=>{title.textContent=answerQuery.value.trim()||'What is an AI agent?'};
document.querySelectorAll('.history').forEach(b=>b.onclick=()=>{answerQuery.value=b.textContent;title.textContent=b.textContent;document.querySelectorAll('.history').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.getElementById('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('nexaTheme',document.body.classList.contains('dark')?'dark':'light');document.getElementById('darkToggle').checked=document.body.classList.contains('dark')};
if(localStorage.getItem('nexaTheme')==='dark'){document.body.classList.add('dark')};document.getElementById('darkToggle').checked=document.body.classList.contains('dark');document.getElementById('darkToggle').onchange=e=>{document.body.classList.toggle('dark',e.target.checked);localStorage.setItem('nexaTheme',e.target.checked?'dark':'light')};
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(document.querySelector('.answer-text').innerText);alert('Answer copied.')}catch{alert('Answer ready to copy.')}};document.getElementById('share').onclick=()=>alert('Share link created.');document.getElementById('save').onclick=()=>alert('Settings saved successfully.');
