const pages=document.querySelectorAll('.page');
function showTab(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));window.scrollTo({top:0,behavior:'smooth'});localStorage.setItem('nexaTab',id)}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));showTab(localStorage.getItem('nexaTab')||'home');

const answers={
'ai': ['What is artificial intelligence?','Artificial intelligence (AI) is the field of creating computer systems that can perform tasks that normally require human intelligence, such as understanding language, recognizing patterns, learning from data, and making decisions.','AI systems commonly work by combining data, algorithms, and computing power. Machine learning is one major approach in which systems learn patterns from examples instead of being programmed with every rule.'],
'machine learning':['What is machine learning?','Machine learning is a branch of AI in which computers learn patterns from data and use those patterns to make predictions or decisions.','A typical workflow includes collecting data, training a model, testing it on unseen examples, and improving the model when its results are not accurate enough.'],
'html':['What is HTML?','HTML (HyperText Markup Language) is the standard language used to structure content on web pages. It defines elements such as headings, paragraphs, links, images, forms, tables, and sections.','HTML provides the structure of a webpage, while CSS controls presentation and JavaScript adds behavior and interaction.'],
'css':['What is CSS?','CSS (Cascading Style Sheets) is used to control the appearance and layout of HTML documents. It can define colors, spacing, typography, grids, animations, and responsive layouts.','CSS separates presentation from document structure, making websites easier to style consistently across many pages and screen sizes.'],
'javascript':['What is JavaScript?','JavaScript is a programming language widely used to add behavior and interactivity to web pages. It can respond to clicks, change page content, validate forms, communicate with servers, and build complete applications.','In browsers, JavaScript can manipulate the DOM, use web APIs, store data locally, and react to events such as clicks and keyboard input.'],
'python':['What is Python?','Python is a high-level, general-purpose programming language known for readable syntax and a large ecosystem of libraries.','It is commonly used for web development, automation, data analysis, artificial intelligence, scientific computing, and education.'],
'database':['What is a database?','A database is an organized system for storing and retrieving information. Databases allow applications to keep data such as users, products, orders, or student records in a structured way.','Relational databases store data in tables and commonly use SQL, while NoSQL databases use models such as documents, key-value pairs, or graphs.'],
'cloud computing':['What is cloud computing?','Cloud computing means using computing resources such as servers, storage, databases, and software over a network instead of managing all of the hardware locally.','Cloud services can scale resources up or down as needed and are commonly offered as infrastructure, platforms, or ready-to-use software.'],
'cybersecurity':['What is cybersecurity?','Cybersecurity is the practice of protecting computers, networks, applications, and data from unauthorized access, disruption, damage, or theft.','Common practices include strong authentication, software updates, encryption, backups, access control, monitoring, and security awareness.'],
'blockchain':['What is blockchain?','A blockchain is a distributed digital ledger in which records are grouped into blocks and linked using cryptographic techniques.','Many blockchain systems are maintained by a network of participants rather than a single central authority. The exact security and governance model depends on the blockchain.'],
'algorithm':['What is an algorithm?','An algorithm is a finite sequence of clear steps used to solve a problem or perform a task.','Examples include sorting algorithms, search algorithms, shortest-path algorithms, and algorithms used by recommendation systems.'],
'data science':['What is data science?','Data science combines statistics, programming, domain knowledge, and data analysis to extract useful insights from data.','A data science workflow can include cleaning data, exploring patterns, creating features, building models, evaluating results, and communicating findings.'],
'iot':['What is the Internet of Things?','The Internet of Things (IoT) refers to physical devices that contain sensors, software, or connectivity so they can collect and exchange data.','Examples include smart watches, connected home devices, industrial sensors, and connected vehicles.'],
'operating system':['What is an operating system?','An operating system is system software that manages computer hardware and provides services for applications.','Examples include Windows, macOS, Linux, Android, and iOS. Operating systems manage processes, memory, files, devices, and user interaction.'],
'git':['What is Git?','Git is a distributed version-control system used to track changes in files, especially source code.','Developers use Git to create commits, branches, merges, and history so they can collaborate and safely manage changes.'],
'github':['What is GitHub?','GitHub is a platform for hosting Git repositories and collaborating on software projects.','It provides features such as pull requests, issues, code review, project management, and automated workflows.'],
'sql':['What is SQL?','SQL (Structured Query Language) is used to work with relational databases. It can retrieve, insert, update, and delete data and can also define database structures.','Common SQL commands include SELECT, INSERT, UPDATE, DELETE, CREATE, and JOIN operations.'],
'api':['What is an API?','An API (Application Programming Interface) is a defined way for software systems to communicate with each other.','A web API may allow an application to request data or perform an action through HTTP endpoints, often using formats such as JSON.'],
'internet':['What is the Internet?','The Internet is a global network of interconnected computer networks that communicate using standardized protocols.','It supports services such as websites, email, file transfer, video calls, messaging, and many other applications.'],
'computer network':['What is a computer network?','A computer network connects devices so they can communicate and share resources.','Networks can range from a small local network in a home or office to large networks spanning cities and countries.'],
'ram':['What is RAM?','RAM (Random Access Memory) is fast, temporary memory used by a computer to hold data and instructions that active programs need.','RAM is volatile, meaning its contents are normally lost when the device is powered off. More RAM can allow a system to handle more active applications and data at once.'],
'cpu':['What is a CPU?','The CPU (Central Processing Unit) is a processor that executes instructions and performs calculations for computer programs.','CPU performance depends on factors such as architecture, clock speed, core count, cache, and the workload being performed.'],
'programming language':['What is a programming language?','A programming language is a formal language used to write instructions that computers can execute or translate into executable programs.','Examples include Python, JavaScript, Java, C, C++, C#, and many others, each suited to different tasks and environments.'],
'web development':['What is web development?','Web development is the process of creating websites and web applications.','Frontend development commonly uses HTML, CSS, and JavaScript, while backend systems can use many languages and databases to provide data and application logic.'],
'responsive design':['What is responsive web design?','Responsive web design is an approach in which a website adapts its layout and content to different screen sizes and devices.','CSS media queries, flexible grids, relative units, and responsive images are common techniques used to create layouts that work on phones, tablets, and desktops.'],
'react':['What is React?','React is a JavaScript library for building user interfaces from reusable components.','React applications commonly represent interface pieces as components and update the UI when application data changes.'],
'pandas':['What is Pandas?','Pandas is a Python library designed for working with structured data. It provides data structures such as DataFrame and Series along with tools for cleaning, transforming, grouping, and analyzing data.','Pandas is widely used in data analysis and is often combined with libraries such as NumPy and Matplotlib.'],
'numpy':['What is NumPy?','NumPy is a Python library for numerical computing. Its main array structure supports efficient operations on multidimensional numerical data.','It provides mathematical functions, array operations, linear algebra tools, random-number utilities, and other foundations used by scientific Python software.'],
'chatgpt':['What is ChatGPT?','ChatGPT is an AI assistant designed to understand prompts and generate natural-language responses.','It can help with tasks such as explaining concepts, writing, brainstorming, coding, summarizing, and problem solving. Its exact capabilities depend on the model and tools available.'],
'generative ai':['What is generative AI?','Generative AI refers to AI systems that can create new content such as text, images, audio, video, or code based on learned patterns.','Generative models are trained on large amounts of data and can produce outputs in response to prompts or other inputs.']
};
function findAnswer(q){const s=q.toLowerCase();for(const k in answers){if(s.includes(k))return answers[k]}return null}
const query=document.getElementById('query'),answerQuery=document.getElementById('answerQuery'),title=document.getElementById('answerTitle'),answerBox=document.querySelector('.answer-text');
function renderAnswer(q){const a=findAnswer(q);if(!a){title.textContent=q;answerBox.innerHTML='<p>Here is a general explanation for your question. Try asking about AI, HTML, CSS, JavaScript, Python, databases, cloud computing, cybersecurity, algorithms, Git, SQL, APIs, web development, science, technology, or travel.</p><h3>Try one of the 30 supported topics</h3><p>Artificial intelligence, machine learning, HTML, CSS, JavaScript, Python, databases, cloud computing, cybersecurity, blockchain, algorithms, data science, IoT, operating systems, Git, GitHub, SQL, APIs, the Internet, computer networks, RAM, CPUs, programming languages, web development, responsive design, React, Pandas, NumPy, ChatGPT, and generative AI.</p>';return}title.textContent=a[0];answerBox.innerHTML='<p>'+a[1]+'</p><h3>In simple terms</h3><p>'+a[2]+'</p>'}
function runSearch(){let q=query.value.trim()||'What is artificial intelligence?';answerQuery.value=q;renderAnswer(q);showTab('answer')}
document.getElementById('searchBtn').onclick=runSearch;query.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();runSearch()}});document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{query.value=b.dataset.q;runSearch()});document.getElementById('answerSearch').onclick=()=>renderAnswer(answerQuery.value.trim()||'What is artificial intelligence?');
document.querySelectorAll('.history').forEach(b=>b.onclick=()=>{answerQuery.value=b.textContent;renderAnswer(b.textContent);document.querySelectorAll('.history').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.getElementById('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('nexaTheme',document.body.classList.contains('dark')?'dark':'light');document.getElementById('darkToggle').checked=document.body.classList.contains('dark')};
if(localStorage.getItem('nexaTheme')==='dark')document.body.classList.add('dark');document.getElementById('darkToggle').checked=document.body.classList.contains('dark');document.getElementById('darkToggle').onchange=e=>{document.body.classList.toggle('dark',e.target.checked);localStorage.setItem('nexaTheme',e.target.checked?'dark':'light')};
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(document.querySelector('.answer-text').innerText);alert('Answer copied.')}catch{alert('Answer ready to copy.')}};document.getElementById('share').onclick=()=>alert('Share link created.');document.getElementById('save').onclick=()=>alert('Settings saved successfully.');
